name: Gerar Relatório Semanal

on:
  schedule:
    - cron: '0 12 * * 1'  # Segunda-feira às 9h BRT (12h UTC)
  workflow_dispatch:

jobs:
  gerar-relatorio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        run: python slack_report.py
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
